### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by limod** [Quobject/docker-cli-js#19]
Hello!
Could you provide a new release version with this feature: https://github.com/Quobject/docker-cli-js/pull/18 (c6176d905575200241c6934d30cf687d1744c6df) ? https://www.npmjs.com/package/docker-cli-js/v/2.7.1 2.7.1 seems too old.

Thanks!

**Comment by mattqs** [comment]
New release: https://github.com/Quobject/docker-cli-js/releases/tag/2.8.0
