### ISSUE TITLE
docker images -q not working

### ISSUE THREAD

**Issue by JannikZed** [Quobject/docker-cli-js#25]
```
const inspect = await docker.command(`images -q ${imageTag}`);
```

results in: 

```
{
  command: 'docker  images -q ghcr.io/trieb-work/XXXXXXXX:3.0.0-b.40',
  raw: '15e892c27a33\n',
  images: []
}
```

**Comment by mattqs** [comment]
You are specifying with the -q parameter that you only want the "image id", which is exactly what you got in "raw". 
The images array does not get filled with the -q parameter. This functionality has not been implemented. You can submit a pull request if you want to do this.
