### ISSUE TITLE
Docker run command does not support passing environment variables

### ISSUE THREAD

**Issue by jbstewart** [Quobject/docker-cli-js#6]
The usefulness of the docker run command with this library is somewhat limited by the fact that when the docker command is exec'd the no environment variables are passed through except  DEBUG, HOME, and PATH.

**Comment by mattqs** [comment]
Which environment variable do you need?

**Comment by jbstewart** [comment]
Well, it's customary to pass credentials like DB usernames and passwords via environment variables, so they could be pretty much any string. One thing that might work would be to allow the user to pass in an environment object, which you could then destructure into the environment object you pass in (overriding DEBUG, HOME and PATH of course).

**Comment by mattqs** [comment]
Please submit a pull request for this feature.

**Comment by paszin** [comment]
fyi, I have no problems with environment variables.
`docker.run("run  -e USER='paszin' [...])`
